# Generated by Django 3.2 on 2022-03-05 22:44

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_transaction_transaction_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loanaccount",
            name="balance",
            field=djmoney.models.fields.MoneyField(
                blank=True, decimal_places=2, default_currency="ZAR", max_digits=10
            ),
        ),
    ]
