# Generated by Django 3.2 on 2022-02-19 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20220219_0716'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanaccount',
            name='accepted_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
