# Generated by Django 3.2 on 2022-03-06 05:16

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_auto_20220306_0515"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="secondary_phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, null=True, region=None, unique=True
            ),
        ),
    ]
